name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.16]
        os: [windows-latest-arm, ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application
        run: go build -o merge_kubeconfig

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: Release v1.0
          draft: false
          prerelease: false

      - name: Upload binaries
        id: upload-binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: merge_kubeconfig

      - name: Deploy to Windows ARM
        if: matrix.os == 'windows-latest-arm'
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: merge_kubeconfig

      - name: Deploy to Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: merge_kubeconfig

      - name: Deploy to macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: merge_kubeconfig
